### ISSUE TITLE
docs: ":vimdoc:" links are broken

### ISSUE THREAD

**Issue by c4rlo** [JNRowe/vim-configs#12]
Hi, I'm the maintainer of vimhelp.org, and I happened to notice that you have some broken links to it, e.g. https://jnrowe-vim.readthedocs.io/ftdetect/index.html has a link to https://vimhelp.org/filetype.txt#ftdetect which should be https://vimhelp.org/filetype.txt.html#ftdetect. I can see it's generated from https://github.com/JNRowe/vim-configs/blob/main/ftdetect/index.rst using a `:vimdoc:` macro; I don't know where that is defined, but it should be updated to generate correct URLs.

**Comment by JNRowe** [comment]
First and most importantly, thanks for running vimhelp.org!

---

Thanks for the report, all should be fixed now.  A touch ashamed to admit the link errors were simply an oversight, and I hadn’t noticed.

FWIW, the expansions are performed via Sphinx’s [extlinks](https://www.sphinx-doc.org/en/master/usage/extensions/extlinks.html) plugin and are configured in [conf.py](https://github.com/JNRowe/vim-configs/blob/main/conf.py#L127).

Thanks,

James
